### PR TITLE
added common navbar and footer to fellows explorer page

### PR DESCRIPTION
**Pull request by mgorkove**
explorer navbar (dektop / tablet / mobile)

Screen Shot 2022-05-23 at 3 59 04 PM
Screen Shot 2022-05-23 at 3 59 46 PM
Screen Shot 2022-05-23 at 4 00 24 PM

### CODE REVIEW

**Comment by mgorkove** [comment]
+ changed styles so that footer sticks to bottom of page

**Review by rorysaur — COMMENTED** [review]
You can actually delete the now-unused `NavBar` component too, as it won't be needed. Otherwise looks good!

**Comment by mgorkove** [comment]
actually, NavBar is used in packages/explorer/src/views/View.js - shall I replace it with the navbar from '@kernel/common' ?

**Comment by rorysaur** [comment]
@mgorkove yes please!

**Review by rorysaur — CHANGES_REQUESTED** [review]
Oops, a few more things, which all involve changes to `App.config.json`:
1. Add `logoUrl` so that the logo shows up. (It's the same as in the `profile` app.)
2. Ensure that clicking on the logo/title in the navbar still sends you to the explorer page and not to the login page. (Add `homeUrl` to the app config, if needed.)
3. Remove all the other navbar links so that it's an empty array.

**Comment by mgorkove** [comment]
@rorysaur I have done the changes!

**Comment by mgorkove** [comment]
> @mgorkove You can delete `src/views/View.jsx` and it's not used. It's an oversight on my part to remove it after setting up the app since I usually copy over a boilerplate.
> 
> I just run the the test workflow and there are a few linting issues. You can simply run the formatter and it should fix these automatically -
> 
> ```
> yarn workspace @kernel/explorer format
> ```
> 
> If you want to see the actual issues, you can run the linter -
> 
> ```
> yarn workspace @kernel/explorer lint
> ```
> 
> Thanks for working on this and welcome!
> 
> How's the dev experience been so far? Anything we can improve or is confusing?

@simonkernel the dev experience has been good so far - my only issue is that whenever I refresh the page, I have to log in again, which slows down the process when I am making changes. Is there a way to disable the login?

**Review by rorysaur — APPROVED** [review]
Looks good!

**Comment by rorysaur** [comment]
@mgorkove for most changes, the hot reloading works so I rarely have to actually refresh.

On the login page, you can set the timeout to the max (1 day) and check the box to auto-authorize. Then if you ever do hit the login page, click "login" and wait a few seconds and it will resolve automatically.

If you really need to disable the auth on a page, you can comment out the `useEffect` that checks the user's role.

I'm still in favor of changing the current behavior because I think it will be frustrating for normal app users also, but for dev we have the above workarounds.

**Comment by simonkernel** [comment]
@mgorkove You need to login because you are making calls to the staging backend. The alternative would be to run the backend locally as well so it's just a trade off.

As @rorysaur pointed out, the intention is to take advantage of hot code reloading preserving state between reloads. During regular development, having to do a hard reload of the page should be the exception.

Can you elaborate on the cases where hot code reload was not working as expected or were you not aware of hot code reload in the first place?

I would like to add something to the contributing guide about the dev workflow around hot code reloading and your feedback would be much appreciated.

**Pull request merged**
